name: 'Release Vscode Plugin'
on:
  push:
    branches:
    - master
jobs:
  marketplacePublish:
    name: Marketplace publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - name: Install dependencies
        run: yarn install
      - name: Publish plugin
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        run: echo $PUBLISHER_TOKEN | ./node_modules/.bin/vsce login enfipy && ./node_modules/.bin/vsce publish --yarn
